export const incompatibleFonts = [
  "Allkin",
  "Chiron GoRound TC",
  "Chiron Sung HK",
  "Chiron Hei HK",
  "Material Icons",
  "Material Icons Outlined",
  "Material Icons Round",
  "Material Icons Sharp",
  "Material Icons Two Tone",
  "Material Symbols Rounded",
  "Material Symbols Outlined",
  "Material Symbols",
  "Material Symbols Sharp",
  "Linefont",
  "Playwrite AR",
  "Playwrite AR Guides",
  "Playwrite AT",
  "Playwrite AT Guides",
  "Playwrite AU NSW",
  "Playwrite AU NSW Guides",
  "Playwrite AU QLD",
  "Playwrite AU SA Guides",
  "Playwrite AU SA",
  "Playwrite AU QLD Guides",
  "Playwrite AU TAS",
  "Playwrite AU TAS Guides",
  "Playwrite AU VIC",
  "Playwrite AU VIC Guides",
  "Playwrite BE VLG",
  "Playwrite BE VLG Guides",
  "Playwrite BE WAL Guides",
  "Playwrite BE WAL",
  "Playwrite BR",
  "Playwrite CA Guides",
  "Playwrite CA",
  "Playwrite CL",
  "Playwrite CL Guides",
  "Playwrite CO",
  "Playwrite BR Guides",
  "Playwrite CU",
  "Playwrite CO Guides",
  "Playwrite CZ Guides",
  "Playwrite CZ",
  "Playwrite CU Guides",
  "Playwrite DE Grund Guides",
  "Playwrite DE Grund",
  "Playwrite DE LA Guides",
  "Playwrite DE LA",
  "Playwrite DE SAS",
  "Playwrite DE SAS Guides",
  "Playwrite DE VA",
  "Playwrite DK Loopet",
  "Playwrite DE VA Guides",
  "Playwrite DK Loopet Guides",
  "Playwrite DK Uloopet",
  "Playwrite DK Uloopet Guides",
  "Playwrite ES",
  "Playwrite ES Deco",
  "Playwrite ES Guides",
  "Playwrite FR Moderne",
  "Playwrite FR Moderne Guides",
  "Playwrite FR Trad",
  "Playwrite FR Trad Guides",
  "Playwrite GB J",
  "Playwrite GB J Guides",
  "Playwrite GB S",
  "Playwrite GB S Guides",
  "Playwrite HR Guides",
  "Playwrite HR",
  "Playwrite HR Lijeva Guides",
  "Playwrite HU",
  "Playwrite HU Guides",
  "Playwrite ID",
  "Playwrite ID Guides",
  "Playwrite IE",
  "Playwrite IE Guides",
  "Playwrite IN",
  "Playwrite IN Guides",
  "Playwrite IS",
  "Playwrite IS Guides",
  "Playwrite IT Moderna",
  "Playwrite IT Moderna Guides",
  "Playwrite IT Trad",
  "Playwrite IT Trad Guides",
  "Playwrite MX",
  "Playwrite MX Guides",
  "Playwrite NG Modern Guides",
  "Playwrite NL",
  "Playwrite NL Guides",
  "Playwrite NG Modern",
  "Playwrite NO Guides",
  "Playwrite NO",
  "Playwrite NZ",
  "Playwrite NZ Basic",
  "Playwrite NZ Basic Guides",
  "Playwrite NZ Guides",
  "Playwrite PE",
  "Playwrite PE Guides",
  "Playwrite PL",
  "Playwrite ES Deco Guides",
  "Playwrite HR Lijeva",
  "Playwrite PL Guides",
  "Playwrite PT Guides",
  "Playwrite PT",
  "Playwrite RO",
  "Playwrite RO Guides",
  "Playwrite SK",
  "Playwrite SK Guides",
  "Playwrite TZ",
  "Playwrite TZ Guides",
  "Playwrite US Modern Guides",
  "Playwrite US Trad",
  "Playwrite VN Guides",
  "Playwrite US Trad Guides",
  "Playwrite VN",
  "Playwrite ZA",
  "Playwrite ZA Guides",
  "Playwrite US Modern",
  "Wavefont"
];