export const incompatibleFonts = [
  "Allkin",
  "Chiron GoRound TC",
  "Chiron Sung HK",
  "Chiron Hei HK",
  "Linefont",
  "Material Icons",
  "Material Icons Outlined",
  "Material Icons Round",
  "Material Icons Sharp",
  "Material Icons Two Tone",
  "Material Symbols Outlined",
  "Material Symbols",
  "Material Symbols Sharp",
  "Material Symbols Rounded",
  "Playwrite AR",
  "Playwrite AR Guides",
  "Playwrite AT",
  "Playwrite AT Guides",
  "Playwrite AU NSW",
  "Playwrite AU NSW Guides",
  "Playwrite AU QLD",
  "Playwrite AU QLD Guides",
  "Playwrite AU SA",
  "Playwrite AU SA Guides",
  "Playwrite AU TAS",
  "Playwrite AU TAS Guides",
  "Playwrite AU VIC",
  "Playwrite AU VIC Guides",
  "Playwrite BE VLG Guides",
  "Playwrite BE VLG",
  "Playwrite BE WAL Guides",
  "Playwrite BR",
  "Playwrite BR Guides",
  "Playwrite CA",
  "Playwrite CA Guides",
  "Playwrite BE WAL",
  "Playwrite CO",
  "Playwrite CO Guides",
  "Playwrite CL Guides",
  "Playwrite CU",
  "Playwrite CZ",
  "Playwrite CU Guides",
  "Playwrite CZ Guides",
  "Playwrite DE Grund",
  "Playwrite DE Grund Guides",
  "Playwrite DE LA Guides",
  "Playwrite DE LA",
  "Playwrite DE SAS Guides",
  "Playwrite DE SAS",
  "Playwrite DE VA",
  "Playwrite CL",
  "Playwrite DE VA Guides",
  "Playwrite DK Loopet",
  "Playwrite DK Loopet Guides",
  "Playwrite DK Uloopet",
  "Playwrite DK Uloopet Guides",
  "Playwrite ES",
  "Playwrite ES Deco",
  "Playwrite ES Deco Guides",
  "Playwrite ES Guides",
  "Playwrite FR Moderne",
  "Playwrite FR Moderne Guides",
  "Playwrite FR Trad",
  "Playwrite FR Trad Guides",
  "Playwrite GB J",
  "Playwrite GB J Guides",
  "Playwrite GB S",
  "Playwrite GB S Guides",
  "Playwrite HR",
  "Playwrite HR Guides",
  "Playwrite HR Lijeva",
  "Playwrite HU",
  "Playwrite HU Guides",
  "Playwrite ID",
  "Playwrite IE",
  "Playwrite ID Guides",
  "Playwrite IE Guides",
  "Playwrite IN",
  "Playwrite IN Guides",
  "Playwrite IS",
  "Playwrite IT Moderna",
  "Playwrite IS Guides",
  "Playwrite IT Moderna Guides",
  "Playwrite HR Lijeva Guides",
  "Playwrite IT Trad Guides",
  "Playwrite IT Trad",
  "Playwrite NG Modern",
  "Playwrite MX",
  "Playwrite MX Guides",
  "Playwrite NG Modern Guides",
  "Playwrite NL",
  "Playwrite NL Guides",
  "Playwrite NO Guides",
  "Playwrite NO",
  "Playwrite NZ Basic",
  "Playwrite NZ Basic Guides",
  "Playwrite PE",
  "Playwrite PE Guides",
  "Playwrite NZ Guides",
  "Playwrite PL Guides",
  "Playwrite PT",
  "Playwrite PT Guides",
  "Playwrite RO",
  "Playwrite RO Guides",
  "Playwrite SK Guides",
  "Playwrite TZ",
  "Playwrite SK",
  "Playwrite PL",
  "Playwrite TZ Guides",
  "Playwrite NZ",
  "Playwrite US Modern",
  "Playwrite US Modern Guides",
  "Playwrite US Trad",
  "Playwrite VN",
  "Playwrite VN Guides",
  "Playwrite ZA",
  "Playwrite ZA Guides",
  "Playwrite US Trad Guides",
  "Wavefont"
];