export const incompatibleFonts = [
  "Allkin",
  "Chiron GoRound TC",
  "Chiron Sung HK",
  "Chiron Hei HK",
  "Linefont",
  "Material Icons",
  "Material Icons Outlined",
  "Material Icons Round",
  "Material Icons Sharp",
  "Material Icons Two Tone",
  "Material Symbols",
  "Material Symbols Outlined",
  "Material Symbols Rounded",
  "Material Symbols Sharp",
  "Playwrite AR",
  "Playwrite AT",
  "Playwrite AT Guides",
  "Playwrite AR Guides",
  "Playwrite AU NSW",
  "Playwrite AU NSW Guides",
  "Playwrite AU QLD",
  "Playwrite AU SA",
  "Playwrite AU SA Guides",
  "Playwrite AU TAS Guides",
  "Playwrite AU VIC",
  "Playwrite AU VIC Guides",
  "Playwrite BE VLG",
  "Playwrite BE VLG Guides",
  "Playwrite BE WAL",
  "Playwrite AU TAS",
  "Playwrite BR",
  "Playwrite AU QLD Guides",
  "Playwrite CA Guides",
  "Playwrite BR Guides",
  "Playwrite CL",
  "Playwrite CA",
  "Playwrite BE WAL Guides",
  "Playwrite CL Guides",
  "Playwrite CO Guides",
  "Playwrite CO",
  "Playwrite CU",
  "Playwrite CU Guides",
  "Playwrite DE Grund",
  "Playwrite CZ Guides",
  "Playwrite CZ",
  "Playwrite DE LA",
  "Playwrite DE SAS",
  "Playwrite DE LA Guides",
  "Playwrite DE SAS Guides",
  "Playwrite DE VA",
  "Playwrite DE VA Guides",
  "Playwrite DK Loopet",
  "Playwrite DK Loopet Guides",
  "Playwrite DK Uloopet",
  "Playwrite DK Uloopet Guides",
  "Playwrite ES",
  "Playwrite ES Deco",
  "Playwrite DE Grund Guides",
  "Playwrite ES Guides",
  "Playwrite ES Deco Guides",
  "Playwrite FR Moderne",
  "Playwrite FR Moderne Guides",
  "Playwrite FR Trad",
  "Playwrite GB J",
  "Playwrite FR Trad Guides",
  "Playwrite GB J Guides",
  "Playwrite GB S Guides",
  "Playwrite GB S",
  "Playwrite HR",
  "Playwrite HR Guides",
  "Playwrite HR Lijeva Guides",
  "Playwrite HU",
  "Playwrite HU Guides",
  "Playwrite ID",
  "Playwrite ID Guides",
  "Playwrite IN",
  "Playwrite IE",
  "Playwrite IN Guides",
  "Playwrite IE Guides",
  "Playwrite IS Guides",
  "Playwrite IT Moderna",
  "Playwrite IT Moderna Guides",
  "Playwrite IT Trad Guides",
  "Playwrite MX",
  "Playwrite MX Guides",
  "Playwrite NG Modern",
  "Playwrite IS",
  "Playwrite NG Modern Guides",
  "Playwrite NL",
  "Playwrite IT Trad",
  "Playwrite NL Guides",
  "Playwrite NO Guides",
  "Playwrite NO",
  "Playwrite NZ",
  "Playwrite NZ Basic",
  "Playwrite NZ Basic Guides",
  "Playwrite PE",
  "Playwrite PE Guides",
  "Playwrite PL",
  "Playwrite PL Guides",
  "Playwrite PT Guides",
  "Playwrite RO Guides",
  "Playwrite RO",
  "Playwrite SK",
  "Playwrite SK Guides",
  "Playwrite TZ Guides",
  "Playwrite US Modern",
  "Playwrite US Modern Guides",
  "Playwrite US Trad",
  "Playwrite US Trad Guides",
  "Playwrite TZ",
  "Playwrite VN",
  "Playwrite VN Guides",
  "Playwrite ZA",
  "Playwrite NZ Guides",
  "Playwrite HR Lijeva",
  "Playwrite PT",
  "Playwrite ZA Guides",
  "Wavefont"
];